### ISSUE TITLE
Odd configuration of one scanner causing issues with Kerbalism

### ISSUE THREAD

**Issue by utoxin** [linuxgurugamer/NSS#11]
While trying to track down an issue with TweakScale and Kerbalism, we found an oddity with how you configured one of the scanners that's breaking Kerbalism's module patches.

Details here: https://github.com/Kerbalism/Kerbalism/issues/477

**Comment by utoxin** [comment]
@linuxgurugamer any chance you'll be able to work on this soon? I could submit a pull request to make the change if you don't have the time.

**Comment by linuxgurugamer** [comment]
I don't support Kerbalism, it does too many different things.  So I don't even try, sorry

Edit:  I just read the original thread, I'll take care of it

**Comment by linuxgurugamer** [comment]
How urgent is this needed?  I can push a quickie, but would like to wait a few days to finish the other changes

**Comment by utoxin** [comment]
As stated on that thread, not urgent for me. I wasn't using any parts from this mod yet.

**Comment by linuxgurugamer** [comment]
Fixed in next release
