### ISSUE TITLE
0.1.7 isn't fully released

### ISSUE THREAD

**Issue by sundhaug92** [linuxgurugamer/NSS#2]
For one, the release hasn't been pushed to spacedock. This causes CKAN to look for v0.1.7 on spacedock and fail on KSP 1.3.x

**Comment by linuxgurugamer** [comment]
Fixed, thanks

**Comment by linuxgurugamer** [comment]
It has a dependency on BDAnimationModules, which hasn't had a full release on CKAN yet, so it won't be visible.  But it is now uploaded to Spacedock
