### ISSUE TITLE
Small error in NSS_MM_TweakScale.cfg

### ISSUE THREAD

**Issue by Atario** [linuxgurugamer/NSS#3]
There's a section like this:

```
@PART[OctoSat_Con_RCS]:NEEDS[TweakScale] 
{
	#@TWEAKSCALEBEHAVIOR[Engine]/MODULE[TweakScale] { }
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 1.25
    }
}
@PART[OctoSat_Pr*]:NEEDS[TweakScale] 
{
    %MODULE[TweakScale]
    {
		#@TWEAKSCALEBEHAVIOR[Engine]/MODULE[TweakScale] { }
        type = stack
        defaultScale = 1.25
    }
}
```

…and it should look like this:

```
@PART[OctoSat_Con_RCS]:NEEDS[TweakScale] 
{
    #@TWEAKSCALEBEHAVIOR[Engine]/MODULE[TweakScale] { }
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 1.25
    }
}
@PART[OctoSat_Pr*]:NEEDS[TweakScale] 
{
    #@TWEAKSCALEBEHAVIOR[Engine]/MODULE[TweakScale] { }
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 1.25
    }
}
```

Messes up the final version of the .cfg, manifesting in-game as incorrect scaling exponents.  (I'm not sure if the first change of the two actually makes any difference, I'm just being a neat freak)

**Comment by linuxgurugamer** [comment]
thanks

**Comment by linuxgurugamer** [comment]
Ummm, are you sure the TWEAKSCALEBEHAVIOR is even needed?  I commented it out in the my local and it seems to be fine.
Can  you check and get back to me, please

**Comment by linuxgurugamer** [comment]
Just realized that you may not see my edit if by email"

Ummm, are you sure the TWEAKSCALEBEHAVIORis even needed? I commented it out in the my local and it seems to be fine.
Can you check and get back to me, please

**Comment by linuxgurugamer** [comment]
NM, I looked into the TS and saw what they were doing.

**Comment by linuxgurugamer** [comment]
Will be fixed in next release
