### ISSUE TITLE
Add TexturesUnlimited patch

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/NSS#4]
https://www.dropbox.com/s/cohqcvx9ohj80yp/TexturesUnlimited_NSS.zip?dl=0

**Comment by linuxgurugamer** [comment]
Will be in next release

**Comment by Mecripp** [comment]
Updated Patch please use this one https://www.dropbox.com/s/culfl4y5trkczje/TexturesUnlimited_NSS.zip?dl=0
and links on forums have been updated also
