### ISSUE TITLE
Satellite part request 'Gravioli Detector'

### ISSUE THREAD

**Issue by jimduchek** [linuxgurugamer/NSS#5]
The satellite contract requests the 'OctoSat gravioli detector', looking at the code it looks like this part is actually the 'OctoSat Science Bundle'.  Not particularly clear.

**Comment by linuxgurugamer** [comment]
I'll update the description for the requested part, to make it clear where the detector is coming from, thanks

**Comment by linuxgurugamer** [comment]
Will be in next release
