### ISSUE TITLE
TexturesUnlimited_NSS.cfg includes a faulty texture reference

### ISSUE THREAD

**Issue by titanin** [linuxgurugamer/NSS#8]
> IDK -- seems pretty well explained from the bit that TU sent to the log:

`ERROR: KSPShaderLoader - Texture could not be located for name: TexturesUnlimited_NSS/Textures/silver for texture slot: _MetallicGlossMap while loading textures for material:`

> means that you tried to reference a texture that doesn't exist.  Fix your texture reference, and the error will go away.  quote by Shadowmage

[https://forum.kerbalspaceprogram.com/index.php?/topic/167450-14x-15x-textures-unlimited-pbr-shader-texture-set-and-model-loading-api/&do=findComment&comment=3486541](url)

Maybe the textures are now in that textureswitch folder?
​

**Comment by titanin** [comment]
I think removing the whole reference should work fine as I found new configs for other mods who do not use texture references at all. I think its deprecated. How do I create a pull request from a forked branch to the master branch? Thx :)

**Comment by linuxgurugamer** [comment]
I'll do it by hand, but to do it, at the main page for the repo, there will be a button called "New pull request".  I've  made other changes to the file, so it's best this time that I do it by hand

**Comment by linuxgurugamer** [comment]
this will be fixed in the next release
